from dagster import DagsterUserError


class DataprocError(DagsterUserError):
    pass
